### ISSUE TITLE
cannot import name 'six' from 'django.utils' in Django 3

### ISSUE THREAD

**Issue by clashthe** [django-helpdesk/django-helpdesk#788]
**Describe the bug**
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Program Files\Python38\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Program Files\Python38\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Program Files\Python38\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Program Files\Python38\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Program Files\Python38\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\Python38\lib\site-packages\helpdesk\models.py", line 17, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (C:\Program Files\Python38\lib\site-packages\django\utils\__init__.py)
Sentry is attempting to send 0 pending error messages

**To Reproduce**
python manage.py migrate

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win10

setting up django3.0 and got this error

**Comment by gwasser** [comment]
I haven't tested django-helpdesk with django 3.0 at all yet, so I'm not too surprised there's problems. I wouldn't anticipate supporting it yet for a while unfortunately. The `devel` branch features helpdesk that works well with django 2.2 LTS, so you might give that a shot although it's not quite released yet.

**Comment by mamtach** [comment]
I had my working app, until few minutes back, when I reinstalled libraries and (djangorestframework-filters, django-filters ) and now seeing following error:
Please help if there a way to fix this.
---------------------------------------------------------------------
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "...\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "...\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "...\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "...\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "...\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "...\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "...\lib\site-packages\django_filters\__init__.py", line 7, in <module>
    from .filterset import FilterSet
  File "...\lib\site-packages\django_filters\filterset.py", line 10, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (...\lib\site-packages\django\utils\__init__.py)

**Comment by gwasser** [comment]
Unfortunately we don't support Django 3 yet. You should be able to force installation of django2 using pip. Something like `pip install django>2,<3` to get the latest release of Django 2 (2.2.x)

**Comment by mamtach** [comment]
Thanks, I am reverting my installations back to django 2.2.8

**Comment by pramodparab** [comment]
current solution reverting installations back to django 2.2.8 from django 3

**Comment by pallavg** [comment]
Hello, has there been any progress on supporting Django 3? Thank you.

**Comment by gwasser** [comment]
Unfortunately not yet. I have not really had the time to work on it. Help
is welcome!

**Comment by gwasser** [comment]
#827

**Comment by gwasser** [comment]
I'm going to close this ticket as sort of a duplicate of #827. There's some volunteers looking at finally finishing up this work as part of hacktober, if anyone would like to volunteer for that effort check out #878 for discussion! Thanks!
