### ISSUE TITLE
Can not Install as a standalone app

### ISSUE THREAD

**Issue by anorouzi** [django-helpdesk/django-helpdesk#799]
**Describe the bug**
I am trying to install as an app inside django to customise it easily. but when going to install it doesn't work. 
After adding the folder to django apps and install the requirement modules and add the helpdesk to settings.py I cant migrate.

The following s the error shown in terminal:

'''
Traceback (most recent call last):
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mydesk/myappdir/helpdesk/templatetags/helpdesk_staff.py", line 10, in <module>
    from helpdesk.decorators import is_helpdesk_staff
  File "/home/mydesk/myappdir/helpdesk/decorators.py", line 7, in <module>
    from django.utils.decorators import available_attrs
ImportError: cannot import name 'available_attrs' from 'django.utils.decorators' (/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/utils/decorators.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/contrib/admin/checks.py", line 76, in check_dependencies
    for engine in engines.all():
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/template/backends/django.py", line 125, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'helpdesk.templatetags.helpdesk_staff': cannot import name 'available_attrs' from 'django.utils.decorators' (/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/utils/decorators.py)
'''

**Expected behavior**
I should be working but dont know whats happening. 

Any comments or advice to get it working?

Thanks for helping

**Comment by gwasser** [comment]
So `django-helpdesk` is not finding the proper imports in Django, which tells me either Django is not properly installed, or you might be using the wrong version of Django.

The currently release only supports Django 2, but the newest Django release is version 3.0. Make sure you have installed Django 2.2, and NOT Django 3 for now.

**Comment by anorouzi** [comment]
I found the problem and fix it and now properly worked with Django 3.0 .As mentioned in here https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis 
django 3.0> no longer supports  from django.utils.decorators import available_attrs.

To solve it simply in decorators.py this line must be removed and also line with :
   @wraps(view_func, assigned=available_attrs(view_func))
must be replaced with: 
    @wraps(view_func)
   thanks for response.

**Comment by gwasser** [comment]
Thanks I'm going to reopen this for now to remind to fix this later.

**Comment by anorouzi** [comment]
And also this changes has to be made to work properly with Django 3.0+ :
{% load staticfiles %} and {% load adminstatic %} were deprecated in Django 2.1, and removed in Django 3.0.

The followings in template files:
```
{% load staticfiles %} 
{% load static from staticfiles %}
{% load adminstatic %}
```
You should replace the tag with simply:
`{% load static %}`
Just for Reminding to be fixed later

**Comment by uhurusurfa** [comment]
@gwasser  - ficed in this commit and can be closed?
https://github.com/django-helpdesk/django-helpdesk/commit/f9f975932b905c061d4d3f9a7304d3b71aa766c0

**Comment by gwasser** [comment]
Yes makes sense to me @uhurusurfa, since it now supports up to Django 4 this issue should be fixed.
