### ISSUE TITLE
get_email attachement issue

### ISSUE THREAD

**Issue by pawelmarkowski** [django-helpdesk/django-helpdesk#466]
Regarding last @reduxionist updates I have a problem with attachment from an email. Attachment has bigger size than original file and it can not be opened. Probably some kind of plain text is added to attached file. I will take a look in a future on that, but maybe author might identify issue faster.

Pawel.

**Comment by reduxionist** [comment]
I'll look into it immediately, it shouldn't matter but just in case, which method of attaching are you using; oubliuc ticket creation, private ticket creation, addition of follow-up, or reply by email?

**Comment by pawelmarkowski** [comment]
Reply by email

**Comment by reduxionist** [comment]
Great, one more detail: roughly what mimetype was the content?

**Comment by reduxionist** [comment]
I had a vague memory of your environment being Python 3 and IMAP, so that's what I tried first and I've already run into two bugs! I apologize for letting them slip through. the test cases I added weren't all mocked, I know there was at least one integration test that went all the way through to writing the incoming attachment out to disk and then reading it back in from the filesystem to compare for equality of UTF8 content -- but I'll add more to cover the current situation and then patch will follow... 🙇

**Comment by pawelmarkowski** [comment]
attachements image/png (new ticket) and application/pdf (update) both unreadable 

User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101
 Thunderbird/45.4.0
MIME-Version: 1.0
Content-Type: multipart/mixed;

**Comment by reduxionist** [comment]
I'm about to push a branch to my fork with a patch that works for me except under Django 1.8 and Python 3 (issue was reproducible with any binary attachment under any Django with Python 3). So if you can give that one a try hopefully it will work for you too while I write the missing tests to cover this scenario properly. Thanks!

**Comment by reduxionist** [comment]
Sorry for the delay, it took me way, way longer to write the commit message than it should have. If this does in fact fix the corrupt binary attachments issue for you  then I will merge it here with some special-cased handling of the Django 1.8 + Python 3 scenario that would currently break the build. My apologies once again for the bug, I actually thought the present version was so much cleaner than the earlier refactoring which is now back in place... 😊

**Comment by reduxionist** [comment]
The results from Travis have just shown me I've broken my local test environment (pyenv + tox not going so well for me today), and it looks like issue is actually worse now because I got the difference in using the std. lib.'s email.message methods backwards and am actually throwing exceptions under Py3 despite what I believed my local testrunner was showing me. I'm going to have to fix my dev env before I can make any sensible approach, so now that at least you know where my code went bad please feel free to apply a fix if you're so inclined. Otherwise, I'll let you know once I'm back on it myself... 🙈

**Comment by pawelmarkowski** [comment]
Hello, sorry for my late reply. I will take a look on it tomorrow evening or day after because I am overloaded last days ;). I hope it will be enough and we will not replicate the same work in the meantime.

**Comment by reduxionist** [comment]
I ended up switching to a new laptop completely but I forgot just how long it takes me to configure a new personal machine as 'comfortable' for daily use; definite fail on the devops at home I'm afraid... Hopefully I'll have updated you before you get to it, but if Ihaven't then ping me in case I've just been distracted by the office... 😉

**Comment by reduxionist** [comment]
Hi @pawelmarkowski, I have at least managed to get the everything but Dajngo1.8 under Python 3 version that I mentioned working as promised. While there's probably an easy solution the Dj1.8+Py3 fail, ow that we've at least made some progress with your particular case I feel I can slow down enough to build some unit tests out of this. One caveat is that we may still mis-encode if we don't get the right mimetype when first receive the attachment and wen can't guess it from the file extension -- but at least for the obvious binaries .pdf and .jpg the corruption is gone from my environment, but do let us know what you see whenever you get a chance to deploy from [my fork](https://github.com/reduxionist/django-helpdesk/tree/hotfix/corrupt-forwarding-of-binary-attachments). Thanks!

**Comment by pawelmarkowski** [comment]
@reduxionist I made couple changes.... illegible attachment regards to encoding issues that are the most difficult in debugging ... :|

**Comment by pawelmarkowski** [comment]
hello, I am back and it is a good time to make some updates and solve some issues :)

I made update on my production server and now I have fresh packages install... Error that I have met:

File "..../helpdesk/management/commands/get_email.py", line 55, in __init__
    self.option_list += (
AttributeError: 'Command' object has no attribute 'option_list'

**Comment by gwasser** [comment]
@pawelmarkowski I believe that comes from trying to use the current release (0.1.18) on Python 3. Unfortunately, that release does not have full Python 3 support. I would recommend trying out the beta of 0.2.0 which is on the master branch right now, it does support Python 3 (in fact, Py3 is the default now).

**Comment by gwasser** [comment]
I pulled in this work in #545 now that Django 1.11 is out and we can switch to it as a base. Thanks for the work everyone! Please let me know if there are still problems with attachments. I'm closing for now so I can do an inventory for what's left for 0.2 release.
