### ISSUE TITLE
Get_email broken under Python 3.5

### ISSUE THREAD

**Issue by BenHagan** [django-helpdesk/django-helpdesk#376]
Let me start by saying than you for keeping this going.  Django is a great platform and needs a good helpdesk app.

Now, when trying to run get_email with Python 3.5.1 and Django 1.9.1 I get errors:

`/helpdesk/management/commands/get_email.py", line 86
    print "Processing: %s" % q
                         ^
SyntaxError: Missing parentheses in call to 'print'`

This makes me think that this code was overlooked during a Python 3.5 port.  I fixed a few print statements in get_email.py but then hit this wall:

`/helpdesk/management/commands/get_email.py", line 102, in process_queue
    socket.socket = socket._socketobject
AttributeError: module 'socket' has no attribute '_socketobject'
`

Just to be sure I went and did another installation under 2.7 and everything works fine.

I'd like to take a stab at fixing this (might need some guidance).  Thoughts?

**Comment by BenHagan** [comment]
I keep working my way through these, but it looks like the whole file is going to need refactoring for python 3.  If that becomes the case, does it become beneficial to create a separate 3.5 branch?

**Comment by rossp** [comment]
@BenHagan thanks for spending some time on this. It should be quite possible to get this working on both 2.7 and 3.5 without having a separate branch - see recent work on #290 and #356 for some examples of this. 

It looks like you're coming across an issue where we've used undocumented and/or internal objects within `socket.socket` which will probably require a bit of troubleshooting to a) identify why it was done like that, and b) make it work on multiple systems.

It's probably easier to backport 3.5-OK code to 2.7 than the alternative - so see if you can get this working and we can go ahead and make it work on older versions too.

**Comment by flinz** [comment]
This functionality should be generally covered by tests, which it obviously is not right now (python 3.5 passes all tests). Adding this to the Testing project.

**Comment by gwasser** [comment]
I have a new get_email test in #420. I'm not sure about the socket issue, not clear to me what it's doing.

**Comment by reduxionist** [comment]
After looking at the socket._socketobject assignment's potential impact in the commit where it first appeared and in a current stable release, I'm led to believe that it has never actually served any purpose at all.

It could be an artifact left over from a refactoring, or perhaps it was part of the pattern used to add the SOCKS support which motivated the commit it originates from, and that part just happens to be unnecessary in our case (it might be helpful if switching back between SOCKS and vanilla sockets, but we don't).

Does the new get_email test you've added in #420 still pass if you just rip this naughty use of private internals right out @gwasser?

**Comment by gwasser** [comment]
Yes, my test only looks at local files (the functionality I added) using mock. Not sure there's a way to test network actions with a mock? (I'm new to this so please someone jump in if you have an idea!).

**Comment by gwasser** [comment]
I should clarify that my test mocks local file access to read an email and create a ticket, so it is checking the email processing functionality, just not the POP3/IMAP part.

**Comment by reduxionist** [comment]
@BenHagan This should be fixed by commit e5c3c4a from the merge of #420 

If still relevant for you, please do test again and let us know the results, thanks!

**Comment by rando305** [comment]
Is there any update on this?  I added the import _socket and socket.socket = _socket.socket to my code.  

I get an AttributeError: '_xocket.socket' object has no attribute 'makefile'

**Comment by reduxionist** [comment]
My apologies for the delay @rando305; although I have patched this locally, it's only as part of a larger rewrite which I haven't finished with testing yet.
I should be able to spend a couple hours on it Tuesday evening, so, at the least, I should have a patched branch available on my personal fork, even if it's not yet got the coverage to merge here officially.
If your need is more urgent than that, however, and if you're not using SOCKs for any of your queues, then you should be able to just leave out the socket assignment completely for Py3... Sorry about the work-around!

**Comment by rando305** [comment]
@reduxionist - thanks for your effort.  I can wait.  I my current workaround is to run get_email from the python27 virtualenv.  
I was trying to use dj_celery to run the get_email daily.   That has not survived the python3 upgrade either.
I've been trying to just use cron tables to do this instead, but I haven't  mastered the art of running cron jobs from the virtualenv?  Any suggestions?

Again - thanks for keeping this moving forward.

**Comment by reduxionist** [comment]
To activate a virtualenv from cron I would try just invoking the venv's interpreter directly, i.e.
``` 
/path_to_project/.virtual_env/bin/python /path_to_project/manage.py get_email 
```
But if you do need a real wrapper around it, more than just a straight shell script, then the best tool for the job that I know of is [Daniel Malament's nori](https://github.com/ocsw/nori) -- which is Py3k compatible (or at least it was when last checked at 3.2).

My work deadline has been pushed to Thursday so I won't get back to this until the weekend now, but if pushing my local branch that fixes this to my personal fork would be helpful then just let me now!

**Comment by rando305** [comment]
I'm seeing a few weird things with 0.2.0

I haven't had a chance to explore it much yet.  I'll check your stuff over
over the weekend.

Thanks

**Comment by gwasser** [comment]
@rando305 please file new tickets for anything else you see in 0.2.0. It's still a development branch essentially (not officially released yet) so we're ironing out bugs. The interface changed a lot, as well as get_email.

**Comment by reduxionist** [comment]
Although we believe that merging PR #463 fixed this bug, and are therefore closing this issue, please don't hesitate to re-open it if you encounter any further incompatibilities between get_email and a supported version of Python. For any other support requests, please open a new issue. Thanks for the feedback and the assistance in helping us wrap-up the last details of this transition! 🍰
